In [1]:
import numpy as np

 1) Scaling:

a) MIN-MAX

Write 2 scaling functions to do min-max scaling. The first, mm_params(), should take in a 2-D data array (rows are samples, columns are features) as input, and return the parameters necessary for scaling each column. The second, mm_scale(), should take in those parameters as well as a 2-D data array (rows are samples, columns are features), and return the corresponding 2-D scaled version of the data.

NOTE: the reason we need to do it this way is so that later you can take in entirely new data and scale it the same way you did before you trained the model.

In [2]:
def mm_params(data): #Must input a np 2D array
        
    min = data.min()
    max = data.max()
    
    return min, max
    
def mm_scale(min, max, data):

    data = data.astype(np.float)#Must convet to float to keep it from rounding to zero and 1.
    print("matrix input:")
    print(data)
    
    for i in range(0, len(data)):
        for j in range(0, len(data[0])):
            
            #Here's where the scaling happens based on the scaling definition we learned.
            data[i][j] = ((data[i][j] - min)/(max - min))
            
    return data

In [3]:
#make a matrix of shape [2, 10] populated with random ints from 0 to 100
matrix = np.random.randint(low=0, high=100, size=[10, 10])

#print our min and max to test function 1
min, max = mm_params(matrix)
print("min:" + str(min) + " max:" + str(max))

#Turn our matrix into scaled values and print to test function 2
matrix = mm_scale(min, max, matrix)
print("matrix output:")
print(matrix)

min:0 max:98
matrix input:
[[ 2.  5. 77. 75. 34. 14. 19. 17. 64. 10.]
 [17. 79. 25. 35.  3. 42. 54. 41. 64. 94.]
 [62. 27. 51. 12. 46. 16. 37.  4. 65. 67.]
 [ 6. 77. 91. 95. 56. 52. 21. 35.  4. 65.]
 [ 6. 98. 12. 45.  0. 58. 26. 17. 23. 40.]
 [76. 33. 96. 63. 14. 98. 97. 82. 53. 96.]
 [76. 30. 67. 93. 85. 78. 96.  4. 72. 87.]
 [29. 49. 95.  3. 98.  5. 15. 55. 32. 31.]
 [52. 80. 13. 92. 65. 26. 89. 23. 98.  8.]
 [60. 63. 18. 27. 15. 37.  7. 20. 67. 98.]]
matrix output:
[[0.02040816 0.05102041 0.78571429 0.76530612 0.34693878 0.14285714
  0.19387755 0.17346939 0.65306122 0.10204082]
 [0.17346939 0.80612245 0.25510204 0.35714286 0.03061224 0.42857143
  0.55102041 0.41836735 0.65306122 0.95918367]
 [0.63265306 0.2755102  0.52040816 0.12244898 0.46938776 0.16326531
  0.37755102 0.04081633 0.66326531 0.68367347]
 [0.06122449 0.78571429 0.92857143 0.96938776 0.57142857 0.53061224
  0.21428571 0.35714286 0.04081633 0.66326531]
 [0.06122449 1.         0.12244898 0.45918367 0.         0.59183673

 b) Standardization

Repeat what you did in part a) for standardization based scaling instead. Call these functions st_params() and st_scale().

In [4]:
def st_params(data):
    
    mean = data.mean()
    deviation = data.std()
    
    return mean, deviation

def st_scale(mean, deviation, data):
    
    data = data.astype(np.float)#Must convert to float to keep from rounding to zero and 1
    print("input matrix")
    print(data)
    
    for i in range(0, len(data)):
        for j in range(0, len(data[0])):
            
            data[i][j] = ((data[i][j] - mean)/(deviation))
    
    return data

In [5]:
#make a matrix of shape [2, 10] populated with random ints from 0 to 100
matrix = np.random.randint(low=0, high=100, size=[10, 10])

#print our min and max to test function 3
mean, deviation = st_params(matrix)
print("mean:" + str(mean) + " deviation:" + str(deviation))

#Turn our matrix into scaled values and print to test function 4
matrix = st_scale(min, max, matrix)
print("output matrix:")
print(matrix)

mean:46.35 deviation:29.49656759692558
input matrix
[[28.  4. 96. 37. 75. 47.  6. 30. 79. 47.]
 [33. 86. 40. 11. 59. 95.  9. 66. 59.  1.]
 [72. 66. 51. 64. 94. 61. 55. 11. 82. 19.]
 [66. 62. 86. 60. 35. 63.  9. 80. 80. 53.]
 [ 4. 91. 14. 27. 69. 91. 62. 94. 78. 71.]
 [ 7. 35. 47. 70. 80. 92. 63.  5. 30. 45.]
 [ 7. 76. 62. 90. 22. 13.  4. 52. 52.  2.]
 [11.  7. 13. 16.  4. 41. 75. 11. 27. 18.]
 [89. 64. 27. 34. 70. 41.  5. 12. 22. 70.]
 [41. 80.  7. 92. 22. 43. 44. 11. 82. 24.]]
output matrix:
[[0.28571429 0.04081633 0.97959184 0.37755102 0.76530612 0.47959184
  0.06122449 0.30612245 0.80612245 0.47959184]
 [0.33673469 0.87755102 0.40816327 0.1122449  0.60204082 0.96938776
  0.09183673 0.67346939 0.60204082 0.01020408]
 [0.73469388 0.67346939 0.52040816 0.65306122 0.95918367 0.62244898
  0.56122449 0.1122449  0.83673469 0.19387755]
 [0.67346939 0.63265306 0.87755102 0.6122449  0.35714286 0.64285714
  0.09183673 0.81632653 0.81632653 0.54081633]
 [0.04081633 0.92857143 0.14285714 0.27551

 2) Confusion Matrices

Write a function, co_mx(), that takes in 2 lists as inputs, one containing predicted labels and the other containing actual labels. The function should return the corresponding confusion matrix, and a list containing the correspondence between row/column index and label.

In [6]:
def co_mx(predicted, actual):
    
    #Be Verbose for troubleshooting
    #print("predictions:")
    #print(predictions)
    #print("actual:")
    #print(actual)
    
    #Create a reference matrix, so that we can see what our confusion matrix looks like on the edges.
    #The matrix Rows are the predicted values, and the columns are the actual values.
    #Get the unique values, and put them in an array. These will go along the sides of our matrix
    values = np.unique(actual)
    reference = np.zeros(shape = [len(values)+1, len(values)+1])
    reference[0][0] = 42  
    
    for i in range(0, len(values)):
        reference[0][i+1] = values[i]
        reference[i+1][0] = values[i]        
   
    #Be Verbose for troubleshooting:
    #print("reference: (Rows = predictions, Columns = actual values)")
    #print(reference)
    
    for i in range(0, len(predicted)):
        
        #Be Verbose for troubleshooting:
        #print("i is: " + str(i))
        
        #where the predicted[i]  value is in the matrix rows. (Along the left 'column' of the Reference matrix)
        rowIndex = np.where(reference[:,0] == actual[i])
        #Be Verbose for troubleshooting:
        #print("Before transformation, rowIndex is: " + str(rowIndex))
        rowIndex = int(rowIndex[0])
        
        #where the actual[i] value is in the matrix columns (Along the top 'row' of the Reference matrix)
        colIndex = np.where(reference[0] == predicted[i])
        #Be Verbose for troubleshooting
        #print("Before transformation, colIndex is: " + str(colIndex))
        colIndex = int(colIndex[0])
        
        #Be Verbose for troubleshooting:
        #print("rowIndex: " + str(rowIndex))
        #print("colIndex:" + str(colIndex))
        reference[rowIndex][colIndex] += 1
        #print("reference:")
        #print(reference)
        
    #Return the array without the helping reference row and column on the top and left.
    #Also return a list of the guesses and actual answers. I'm not sure what exactly the instructions for the list meant,
    #So I'll just return the list of numbers that would appear both on the top and side of the matrix. (predictions and 
    #actual values are identical in this respect, just located on different "sides" of the matrix.)
    matrix = reference[1:, 1:]
    predictions = reference[1:,0] #The leftmost column is our predictions
    actual = reference[0][1:] #The topmost row is our actual values
    
    return matrix, predictions

#Generate some random 1D arrays to toss into this function as a test. 
#We need to make sure they only fall into the same classes, so I randomly shuffle the predictions to get the actual answers.
#We also can't have duplicates in the "actual" list.
actual = np.arange(10)
predictions = actual.copy()
np.random.shuffle(predictions)

co_mx(predictions, actual)

(array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]]),
 array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]))

 3) Precision/Recall

Write 2 functions, prec() and recall(), that take in 2-D confusion matrices and return the corresponding precision and recall.


NOTE:
Note on HW 3
Rohan Loveland
No unread replies. No replies.

Hi all - for Precision and Recall you can assume the input confusion matrix is binary (ie 2x2).  In general, though, assume the other problems are multi-class (i.e. they should work for N classes).



In [7]:
#I'm assuming the matrix is structured like so:
#
#                       Correct Answers
#
#               True Positive  | True Negative
#     Guesses   ---------------|---------------
#               False Positive | False Negative        
#                           
#

def prec(matrix):
    
    TP = matrix[0][0]
    FP = matrix[1][0]
    
    precision = TP/(TP+FP)
    return precision

def recall(matrix):
    
    TP = matrix[0][0]
    FN = matrix[1][1]
    
    recall = TP/(FN + TP)
    return recall
    
test_matrix = [[2, 4],[5, 3]] 

print("precision: ")
print(prec(test_matrix))

print("recall: ")
print(recall(test_matrix))

precision: 
0.2857142857142857
recall: 
0.4


 3) Testing

Generate your own data (random or made-up) to test each of your functions, and include cells in Jupyter showing your tests ofthe functions after you define them.


Deliverables:

Jupyter Notebook code.

In [ ]:
#I implemented tests in each cell