In [2]:
import numpy as np

 1) Scaling:

a) MIN-MAX

Write 2 scaling functions to do min-max scaling. The first, mm_params(), should take in a 2-D data array (rows are samples, columns are features) as input, and return the parameters necessary for scaling each column. The second, mm_scale(), should take in those parameters as well as a 2-D data array (rows are samples, columns are features), and return the corresponding 2-D scaled version of the data.

NOTE: the reason we need to do it this way is so that later you can take in entirely new data and scale it the same way you did before you trained the model.

In [213]:
def mm_params(data): #Must input a np 2D array
        
    min = data.min()
    max = data.max()
    
    return min, max
    
def mm_scale(min, max, data):

    for i in range(0, len(data)):
        for j in range(0, len(data[0])):
            
            #Here's where the scaling happens based on the scaling definition we learned.
            data[i][j] = ((data[i][j] - min)/(max - min))
    
    return data

In [422]:
#make a matrix of shape [2, 10] populated with random ints from 0 to 100
matrix = np.random.randint(low=0, high=100, size=[10, 10])
print(matrix)

#print our min and max to test function 1
min, max = mm_params(matrix)
print("min:" + str(min) + " max:" + str(max))

#Turn our matrix into scaled values and print to test function 2
matrix = mm_scale(min, max, matrix)
print(matrix)

[[37 55 48 40 20 31 28 21 81 59]
 [16 68 24 59 23 72 29 34 19 92]
 [65 62 36 67  2 31 62 81 81 99]
 [62 13 64 20 62 75 79 39 24 10]
 [12 10 86 54 22 91 58 92 63  7]
 [93 90 96 53 78 80 26 83 28 27]
 [10 85 33 20 20 75 24 28 12  8]
 [32 37 61 20 71 29  5  8 80 91]
 [ 9 84 44 92 50 51 18 23 38 89]
 [34 40 22 80 26 48 21  6 83 52]]
min:2 max:99
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


 b) Standardization

Repeat what you did in part a) for standardization based scaling instead. Call these functions st_params() and st_scale().

In [426]:
def st_params(data):
    
    mean = data.mean()
    deviation = data.std()
    
    return mean, deviation

def st_scale(mean, deviation, data):
    
    for i in range(0, len(data)):
        for j in range(0, len(data[0])):
            
            data[i][j] = ((data[i][j] - mean)/(deviation))
    
    return data

In [591]:
#make a matrix of shape [2, 10] populated with random ints from 0 to 100
matrix = np.random.randint(low=0, high=100, size=[10, 10])
print(matrix)

#print our min and max to test function 3
mean, deviation = st_params(matrix)
print("mean:" + str(mean) + " deviation:" + str(deviation))

#Turn our matrix into scaled values and print to test function 4
matrix = st_scale(min, max, matrix)
print(matrix)

[[74 88 55  9 76 98 76 90 66 80]
 [60  1  2 50 21 55 40 62 29 59]
 [58 55 99 47 56 63 21 43 36 68]
 [98 14 27 11 34 22 22 39 88 31]
 [61 62 63 66  4 77 35 32 29 74]
 [73 76 95 34 76 20 54 34 23 60]
 [87 54 90 45 73 62 89 25  5 10]
 [84 96 81 17 32 33 55 42 86 65]
 [ 7  5 65 72 67 94 93 42 80  1]
 [73 51 39 23 86 39 45 83 20 98]]
mean:52.85 deviation:27.690566985888896
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


 2) Confusion Matrices

Write a function, co_mx(), that takes in 2 lists as inputs, one containing predicted labels and the other containing actual labels. The function should return the corresponding confusion matrix, and a list containing the correspondence between row/column index and label.

In [133]:
def co_mx(predicted, actual):
    
    #Be Verbose for troubleshooting
    #print("predictions:")
    #print(predictions)
    #print("actual:")
    #print(actual)
    
    #Create a reference matrix, so that we can see what our confusion matrix looks like on the edges.
    #The matrix Rows are the predicted values, and the columns are the actual values.
    #Get the unique values, and put them in an array. These will go along the sides of our matrix
    values = np.unique(actual)
    reference = np.zeros(shape = [len(values)+1, len(values)+1])
    reference[0][0] = 42  
    
    for i in range(0, len(values)):
        reference[0][i+1] = values[i]
        reference[i+1][0] = values[i]        
   
    #Be Verbose for troubleshooting:
    #print("reference: (Rows = predictions, Columns = actual values)")
    #print(reference)
    
    for i in range(0, len(predicted)):
        
        #Be Verbose for troubleshooting:
        #print("i is: " + str(i))
        
        #where the predicted[i]  value is in the matrix rows. (Along the left 'column' of the Reference matrix)
        rowIndex = np.where(reference[0] == predicted[i])
        #Be Verbose for troubleshooting:
        #print("Before transformation, rowIndex is: " + str(rowIndex))
        rowIndex = int(rowIndex[0])
        
        #where the actual[i] value is in the matrix columns (Along the top 'row' of the Reference matrix)
        colIndex = np.where(reference[:,0] == actual[i])
        #Be Verbose for troubleshooting
        #print("Before transformation, colIndex is: " + str(colIndex))
        colIndex = int(colIndex[0])
        
        #Be Verbose for troubleshooting:
        #print("rowIndex: " + str(rowIndex))
        #print("colIndex:" + str(colIndex))
        reference[rowIndex][colIndex] += 1
        #print("reference:")
        #print(reference)
        
    #Return the array without the helping reference row and column on the top and left.
    #Also return a list of the guesses and actual answers.
    matrix = reference[1:, 1:]
    predictions = reference[0][1:]
    actual = reference[0][1:]
    
    return matrix, predictions, actual

#Generate some random 1D arrays to toss into this function as a test. 
#We need to make sure they only fall into the same classes, so I randomly shuffle the predictions to get the actual answers.
#We also can't have duplicates in the "actual" list.
actual = np.arange(10)
predictions = actual.copy()
np.random.shuffle(predictions)

co_mx(predictions, actual)

(array([[0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]]),
 array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]))

 3) Precision/Recall

Write 2 functions, prec() and recall(), that take in 2-D confusion matrices and return the corresponding precision and recall.


NOTE:
Note on HW 3
Rohan Loveland
No unread replies. No replies.

Hi all - for Precision and Recall you can assume the input confusion matrix is binary (ie 2x2).  In general, though, assume the other problems are multi-class (i.e. they should work for N classes).



 3) Testing

Generate your own data (random or made-up) to test each of your functions, and include cells in Jupyter showing your tests ofthe functions after you define them.


Deliverables:

Jupyter Notebook code.